
name: FrontEnd Actions

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./Obligatorio/MinTurFrontend

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '13.0.0'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build 
